### ISSUE TITLE
火车收货第三个位置是自动收不到的

### ISSUE THREAD

**Issue by soamber** [Dwayneten/JGM-Automator#1]
你好,我用了自动收货脚本 ,发现火车第三个位置的史诗货物是收不到,连接的MUMU模拟器,不知道是什么原因!

**Comment by Dwayneten** [comment]
分辨率是 1920 * 1080 吗
是所有第三个位置的史诗货物收不到还是某个建筑的货物出现在第三位置时收不到呢

**Comment by soamber** [comment]
我观察了在第三个位置出现的史诗货物都收不到!

**Comment by Dwayneten** [comment]
我这边用大小号在不同两台电脑上试了都没出现这种情况
你把 cv.py 里第`47`行的`if rank < 0.82:`改成更低的比如`if rank < 0.75:试试呢`

**Comment by TanMengyuan** [comment]
我也遇到这个问题了，第三个火车是紫色的话似乎检测不到，调整到0.75也没有效果。Mac下使用Mumu模拟器遇到的这个问题。

**Comment by TanMengyuan** [comment]
> 我也遇到这个问题了，第三个火车是紫色的话似乎检测不到，调整到0.75也没有效果。Mac下使用Mumu模拟器遇到的这个问题。

噢，好像只有第三个火车是钢铁厂的时候会出现这个问题。其他时候没有发现有问题。

**Comment by Dwayneten** [comment]
> > 我也遇到这个问题了，第三个火车是紫色的话似乎检测不到，调整到0.75也没有效果。Mac下使用Mumu模拟器遇到的这个问题。
> 
> 噢，好像只有第三个火车是钢铁厂的时候会出现这个问题。其他时候没有发现有问题。

可能是第三个货箱那有一层薄雾吧 我只送史诗货物 没碰到不送的情况
其他的货物截图都是别人截的 如果不能解决可以考虑自己截一个替换掉

如果是 QQ 账号登陆的话最后的办法（微信听说好像要重新授权）是开最近更新的自动刷新火车功能 没识别到直接刷新火车 总体效率上影响不大

**Comment by TanMengyuan** [comment]
> > > 我也遇到这个问题了，第三个火车是紫色的话似乎检测不到，调整到0.75也没有效果。Mac下使用Mumu模拟器遇到的这个问题。
> > 
> > 
> > 噢，好像只有第三个火车是钢铁厂的时候会出现这个问题。其他时候没有发现有问题。
> 
> 可能是第三个货箱那有一层薄雾吧 我只送史诗货物 没碰到不送的情况
> 其他的货物截图都是别人截的 如果不能解决可以考虑自己截一个替换掉
> 
> 如果是 QQ 账号登陆的话最后的办法（微信听说好像要重新授权）是开最近更新的自动刷新火车功能 没识别到直接刷新火车 总体效率上影响不大

嗯嗯应该是那一块的雾导致识别不到的，不过基本没什么影响。
