### ISSUE TITLE
模拟器很卡

### ISSUE THREAD

**Issue by qq4199** [Dwayneten/JGM-Automator#2]
想问一下作者大大用的是mumu么，夜神执行一段时间后卡的要死，不执行没事

**Comment by Dwayneten** [comment]
是用的 mumu

**Comment by qq4199** [comment]
希望加一个收完指定等级的货物后，如果火车还不走的话重启app，这样省好多时间。

**Comment by qq4199** [comment]
> 是用的 mumu

希望加一个收完指定等级的货物后，如果火车还不走的话重启app，这样省好多时间

**Comment by Dwayneten** [comment]
> > 是用的 mumu
> 
> 希望加一个收完指定等级的货物后，如果火车还不走的话重启app，这样省好多时间

eb212b9b9cbc1a581cc571af35ec9c462dd608ab
